### ISSUE TITLE
Wallet encrytion takes too long

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#116]
It takes 2580ms to encrypt a wallet? That's way too long. Why is that?

**Comment by jennazenk** [comment]
it's a one liner, just a call to ethers library : https://github.com/melonproject/melon.js/blob/parityExp/lib/utils/wallet/encryptWallet.js#L4

**Comment by jennazenk** [comment]
Closing this @schmidsi, pls reopen if needed
