### ISSUE TITLE
Function arguments

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#124]
Related to #113. 

Some functions [1](https://github.com/melonproject/melon.js/blob/parityExp/lib/exchange/transactions/cancelOrderFromAccount.js) have this signature:

```
cancelOrderFromAccount(wallet, id)
```

while others [2](https://github.com/melonproject/melon.js/blob/parityExp/lib/exchange/transactions/makeOrderFromAccount.js) have this one:

```
await makeOrderFromAccount({wallet, sell, buy, timeout})
```

It is understandable that in the second case you want to reduce the number of arguments of the function which can bother the developer.

I think each of the arguments must have his own meaning on the function call. Otherwise, you move the troublesome from having many arguments to having a big dictionary with many values combined.

The developer would end up doing this

```
const obj = {
    wallet: ...

    // transaction objs
    sell: ...,
    buy: ...,

    // options
    timeout: ...
}

await makeOrderFromAccount(obj)
```

IMHO, we should do something like this:

```
const arguments = {
   sell: ...,
   buy: ...
}

const options = {
   timeout: ...
}

await makeOrderFromAccount(wallet, arguments, options)
```

In this way, the number of arguments for the transaction does not affect the number of parameters of the function. 

Besides, I think we should not be afraid of having > 4 parameters on the function if we keep the same signature for all the transactions. However, If we have > 4 I am pretty sure there must be a way to cluster values in group objects as in the example

**Comment by schmidsi** [comment]
+1 for a clear function arguments rule. 

I like the
```
await doSomething(wallet, arguments, options)
```

approach, but a clearer description what is a argument and what an option would be helpful.

I'm also not afraid of > 4 parameters if it makes sense. For me it is just a rule of thumb or a code smell if I see a function with more than 3 arguments (that's why the eslint rule is on warning and not on error). In 90% it is just bad design, in 10% there is a good reason for it.

**Comment by ferranbt** [comment]
Let say we have a function doSomething(args) which internally sends two transactions a(args1) and b(args2). Arguments in doSomething should be the arguments for the transactions.

In options we can add things related to how to handle the transaction itself: timeout, gasLimit, gasPrice...

**Comment by schmidsi** [comment]
In other words:
Arguments: Arguments to the protocol/smart-contracts (what). Including msg.sender.
Options: Knobs to tweak this stuff. (How)

And yeah, merging oft args1 and args2 seems like a good idea.

**Comment by jennazenk** [comment]
Addressed in https://github.com/melonproject/melon.js/pull/177
