### ISSUE TITLE
Create wallet returns mnemonic

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#125]
In [createWallet](https://github.com/melonproject/melon.js/blob/parityExp/lib/utils/wallet/createWallet.js#L5) we should return the mnemonic alongside with the wallet object, otherwise, it is lost forever and the account cannot be recovered.

**Comment by jennazenk** [comment]
The mnemonic is on the wallet object

**Comment by ferranbt** [comment]
Closing.
