### ISSUE TITLE
Use getConfig instead of tokeninfo creates circular dependency

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#132]
From my work on #126.

If we use getConfig instead of tokenInfo to get the address of the assets of the pricefeed we need to do getAddress, getSymbol, getDecimals and getTokenInfo as async functions.

From my perspective, this implies two problems. 
- We need to rewrite a substantial part of the code to add 'await' into the calls of this functions. Besides, all the functions calling this ones which were sync have to become async. This is specially worrying for structures like [this](https://github.com/melonproject/melon.js/blob/c601d1e9508790e5f1d5403a92b32fbad548222f/lib/exchange/calls/getFundRecentTrades.js#L57) where we need to wrap the 'each' calls in Promise.all structures. The more code we have to write the more prone to errors we are.

- Calling functions like getBalance (I haven't tried with others yet) creates a circular dependency of function calls:

```
getBalance
getTokenContract
getAddress
getConfig
getSymbol
getConfig
getSymbol
...
```

The only option I see right now is to setup all the config variables and the pricefeed assets at the beginning so we can avoid await in the pricefeed asset functions (i.e. getSymbol).

**Comment by schmidsi** [comment]
#93 is open to discussion and not mandatory. I thought it would be nice to remove setup and move to a strict functional/pureish style, but these are big arguments to stick to it. That said, I still think we should leave setup as short as possible.

**Comment by ferranbt** [comment]
In this case we are talking about a different setup. Right now, setup only takes the initial arguments but the setup I talked about has to be completely asynchronous because the calls are async.

**Comment by schmidsi** [comment]
Yes. +1 for a bigger async setup.

**Comment by jennazenk** [comment]
TokenInfo is now exposed in the protocol pck. We can't get the lists of supported assets from any contracts in the protocol so we get them from the tokenInfo file exposed in the protoco pck.
