### ISSUE TITLE
fundInformations.inception is always 1. Jan 1970 01:00

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#154]
1. Jan 1970 01:00 == '0000'

It is in the interface like used in melon.js: https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/FundInterface.sol#L49

But I couldn't find the implementation in: https://github.com/melonproject/protocol/blob/v0.6.2-deploy.9/src/Fund.sol

Maybe I'm missing something or this function isn't implemented.

**Comment by jennazenk** [comment]
fixed in 0.6 branch
