### ISSUE TITLE
Remove daemonAddress

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#170]
https://github.com/melonproject/melon.js/blob/master/lib/utils/setup.js#L12

- [ ] Remove also in ipfs-frontend

**Comment by jennazenk** [comment]
addressed in https://github.com/melonproject/melon.js/pull/177

**Comment by schmidsi** [comment]
https://github.com/melonproject/melon.js/search?utf8=%E2%9C%93&q=daemonAddress&type=

**Comment by jennazenk** [comment]
Same here. It is only left in the unit tests, which we need to rewrite anyway and which are not functional at the moment.
