### ISSUE TITLE
getRanking error

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#174]
Using getRanking in the microservice in rankin.melon.fund. Sometimes work without errors but others returns this error message:

```
TypeError: Cannot read property 'times' of undefined
```

which I think comes from [here](https://github.com/melonproject/melon.js/blob/1b49088ff724c6bef7ed5c80b498833a8f6cef8a/lib/version/calls/getRanking.js#L71)

**Comment by jennazenk** [comment]
@ferranbt when you have workaround with db in microservice, can you make a PR pls ? thx

**Comment by schmidsi** [comment]
We need to check if ```fundInceptions[index]``` is defined before calculating here:

```javascript
 inception: new Date(fundInceptions[index].times(1000).toNumber()),
```

**Comment by schmidsi** [comment]
@ferranbt Does this issue still exist? Do you have a workaround?

**Comment by ferranbt** [comment]
I found the issue, getRanking [uses](https://github.com/melonproject/melon.js/blob/3dec6f490688f76fb3f4301c5c09d0251a6b704e/lib/version/calls/getRanking.js#L26) lastFundId from the version contract as a way to know the number of contracts, however, this number do not match the real number of contracts. [Here](https://github.com/melonproject/melon.js/blob/3dec6f490688f76fb3f4301c5c09d0251a6b704e/lib/version/calls/getRanking.js#L32) and [here](https://github.com/melonproject/melon.js/blob/3dec6f490688f76fb3f4301c5c09d0251a6b704e/lib/version/calls/getRanking.js#L34) returns undefined but [here](https://github.com/melonproject/melon.js/blob/3dec6f490688f76fb3f4301c5c09d0251a6b704e/lib/version/calls/getRanking.js#L35) needs to apply the function times to the value and fails.

**Comment by jennazenk** [comment]
I think this happens when [this](https://github.com/melonproject/melon.js/blob/1b49088ff724c6bef7ed5c80b498833a8f6cef8a/lib/version/calls/getRanking.js#L51) returns empty data for some reason.

**Comment by ferranbt** [comment]
Currenltly output returns one fund, but the value in lastFundId is two, so it tries to do more iterations than values in the array. I just made a PR for that.
