### ISSUE TITLE
Malicious html scripts stored on-chain and executed on all clients opening ipfs-frontend

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/melon.js#185]
Related https://github.com/melonproject/protocol/issues/400

Ideally melon.js parses on-chain data s.t. script execution becomes impossilbe on ipfs-frontend - but happy for other suggestions

**Comment by schmidsi** [comment]
Are we talking about XSS with something like a fund named "<script>alert("I extracted your private key")</script>Malicious fund"?

React escapes all values automatically (afaik, It's easy to verify) so that shouldn't be an issue.

**Comment by retotrinkler** [comment]
> Are we talking about XSS with something like a fund named "<script>alert("I extracted your private key")</script>Malicious fund"?

yeah

> React escapes all values automatically (afaik, It's easy to verify) so that shouldn't be an issue.

ok closing this issue again as resolved
