### ISSUE TITLE
Performance bottleneck in getConfig

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#190]
Right now, the function getConfig calls 4 other functions: getNetwork, getNativeAssetSymbol, getQuoteAssetSymbol and getWhiteListedAssets. The first three, make one RPC call each one, the last one, 'getWhiteListedAssets' makes one RPC call per each asset.

Every function on melon.js has to call at the beginning to getConfig, and that creates two problems:
- The number of RPC calls its huge, since we are making like 10 unnecessary calls every time we want to interact with the protocol.
- There have been issues before (with getRanking()) with the memory consumption of melon.js. Its unclear if the problem comes from melon.js or parity.js, what its clear and proved is that the more objects we create the more memory consumption. Right now, getConfig could be creating up to 10 new objects easily every time we call it.

**Comment by schmidsi** [comment]
getConfig only does this one time which is reasonable and caches the result, i.e. subsequent calls to this function do not query the blockchain again:

https://github.com/melonproject/melon.js/blob/master/lib/version/calls/getConfig.js#L45

The function getWhiteListedAssets is indeed a bit overkill, but we are working on a solution here: https://github.com/melonproject/protocol/issues/318 and https://github.com/melonproject/protocol/issues/407.

If you have any other ideas for further performance improvements, feel free to reopen this issue with

**Comment by ferranbt** [comment]
My bad on that, I miss that point.
