### ISSUE TITLE
Add param to getParityProvider to provide own RPC endpoint

### ISSUE THREAD

**Issue by ferranbt** [melonproject/melon.js#193]
I have not checked the whole code so I do not know if this functionality is already available. On the example you use 'getParityProvider' to connect to a local node. However, I really need to be able to connect to a remote node (i.e. infura), I have seen a guay to connect to our 'kovan.melonport.com' nodes, but no easy way to connect to an arbitrary endpoint.

This is my workaround:
```
var {getRanking} = require('@melonproject/melon.js');

const api = new Api(new Api.Provider.Http('https://mainnet.infura.io'));
getRanking({api})
```

**Comment by jennazenk** [comment]
That's because we want to enforce local node for main net connections.  If there is no local node, then it fallbacks to our hosted Kovan node.  We could add more options there, but I think it was voluntary to not allow anything else than either **LOCAL NODE (LIVE or KOVAN) || KOVAN HOSTED NODE**

**Comment by ferranbt** [comment]
That may be a solution for the frontend, but it is a cumbersome approach with servers. The intention on the long term was to use light microservices on Nomad to run the applications, those microservices would point to a specific endpoint to connect to the node. It is not a scalable solution if we have to have a single vm for each service with parity syncing on every one.

**Comment by schmidsi** [comment]
We can give the possibility to specify your RPC endpoint. I rename this issue to reflect the actual TODO.

**Comment by schmidsi** [comment]
Precondition of this: https://github.com/melonproject/simple-trading-bot/issues/5

**Comment by schmidsi** [comment]
https://github.com/melonproject/frontend-lab/pull/33/commits/46685e311b73dfeec51fe6925d8f2d5a261d3ca2
