### ISSUE TITLE
switch to parity.js

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/melon.js#69]
https://github.com/paritytech/js-api

**Comment by schmidsi** [comment]
Should work with https://github.com/paritytech/js-api/issues/6

Other features that we need that I don't know if parity.js supports it:
- [ ] Parsing raw events
- [ ] In-Browser account management (independent of MetaMask or a running parity node)
- [ ] Blockstream?

**Comment by retotrinkler** [comment]
https://docs.ethers.io/ethers.js/html/api-advanced.html#interface might also be option

**Comment by retotrinkler** [comment]
alternative option for blockstream https://github.com/paritytech/oo7-parity

**Comment by jennazenk** [comment]
Fixed in ParityExp branch
