### ISSUE TITLE
Generate keys in webapp

### ISSUE THREAD

**Issue by retotrinkler** [melonproject/melon.js#70]
linked to #69

could be something https://github.com/paritytech/parity/wiki/JSONRPC-parity_accounts-module#parity_newaccountfromphrase

where phrase is generated and stored (encrypted) locally - best solution needs to be researched

This allows for mobile usage and we can move away from metamask

**Comment by schmidsi** [comment]
It's important to note that the private-keys have to be in the browser only.

Here is [the docs for this feature in web3.js](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#create) (But we aim to not use web3.js if possible)

**Comment by schmidsi** [comment]
Metamask has a similar feature here: https://github.com/MetaMask/mascara

But we aim to be able to do it even without Metamask, Metamascara.

Here the ethjs module for this: https://github.com/ethjs/ethjs-account

**Comment by schmidsi** [comment]
Other solution: https://github.com/ethereumjs/keythereum

**Comment by schmidsi** [comment]
Or: https://docs.ethers.io/ethers.js/html/

**Comment by jennazenk** [comment]
Fixed in ParityExp branch
