### ISSUE TITLE
Move to parity.js

### ISSUE THREAD

**Issue by jennazenk** [melonproject/melon.js#77]

**Comment by jennazenk** [comment]
Think this one is the right repo: https://github.com/paritytech/js-api

**Comment by schmidsi** [comment]
Should work with https://github.com/paritytech/js-api/issues/6

Other features that we need that I don't know if parity.js supports it:
- [ ] Parsing raw events
- [ ] In-Browser account management (independent of MetaMask or a running parity node)
- [ ] Blockstream?

**Comment by schmidsi** [comment]
Duplicate of #69
