### ISSUE TITLE
Switch to Typescript

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#80]
To align more with the ecosystem (0x.js) and because it seems that Flowtype doesn't get much traction and gets [left behind](https://twitter.com/ariaminaei/status/927497304470417408) we should switch to Typescript.

**Comment by retotrinkler** [comment]
Hmm would wait w this - as improvements/differences seem small

**Comment by schmidsi** [comment]
We decided to go with Flow types in general
