### ISSUE TITLE
Remove setup

### ISSUE THREAD

**Issue by schmidsi** [melonproject/melon.js#93]
I think the pattern with a global setup call is bad. Better would be:
- Making all functions pure so that they either need the contract instance or the web3 instance as param
- Simplify using it by introducing classes

**Comment by jennazenk** [comment]
Addressed in https://github.com/melonproject/melon.js/pull/177

**Comment by schmidsi** [comment]
It's still around: https://github.com/melonproject/melon.js/blob/master/lib/utils/setup.js

We need to remove this and refactor all dependencies.
